#!/usr/bin/bash

if [[ $1 == "" ]]; then
    unset 'AWS_PROFILE'
else
    cat $HOME/.aws/credentials | grep "\[$1\]"
    if [[ $? != 0 ]]; then
        echo "Profile not found. Try 'aws configure'."
    else
        export AWS_PROFILE=$1
        echo "Successfully switched to profile $1"
    fi
fi
